### ISSUE TITLE
Django 1.9+

### ISSUE THREAD

**Issue by pnovotnak** [red56/django-immutablemodel#9]
Seems like Django 1.9 is not supported;

```
Traceback (most recent call last):
  File "/Users/pnovotnak/myproject/env/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/pnovotnak/myproject/env/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/Users/pnovotnak/myproject/env/lib/python3.5/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/Users/pnovotnak/myproject/env/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/pnovotnak/myproject/env/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/pnovotnak/myproject/env/lib/python3.5/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/pnovotnak/myproject/env/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/pnovotnak/myproject/env/lib/python3.5/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/pnovotnak/myproject/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/pnovotnak/myproject/ego/catalog/models.py", line 35, in <module>
    class Product(ImmutableModel):
  File "/Users/pnovotnak/myproject/ego/src/django-immutablemodel/immutablemodel/models.py", line 62, in __new__
    registered_model = models.base.ModelBase.__new__(cls, name, bases, attrs)
  File "/Users/pnovotnak/myproject/env/lib/python3.5/site-packages/django/db/models/base.py", line 108, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/Users/pnovotnak/myproject/env/lib/python3.5/site-packages/django/db/models/base.py", line 307, in add_to_class
    value.contribute_to_class(cls, name)
  File "/Users/pnovotnak/myproject/env/lib/python3.5/site-packages/django/db/models/options.py", line 255, in contribute_to_class
    raise TypeError("'class Meta' got invalid attribute(s): %s" % ','.join(meta_attrs.keys()))
TypeError: 'class Meta' got invalid attribute(s): mutable
```

**Comment by pnovotnak** [comment]
I'm vaguely aware of changes to Django that make adding stuff to `.Meta` unsupported, but not sure on the details. Does this seem like a simple fix?

**Comment by timdiggins** [comment]
@pnovotnak sorry for rather long wait for my response -- I'm not developing on Django any more, so this project isn't on top of my priorities right now. Will support a PR that brings cross-django-version testing and implementation...
